import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const words = [
  // ─── TIER A — BRONZ (A1) ───────────────────────────────────────────────
  { word: 'cat',        translation: 'kedi',         language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'dog',        translation: 'köpek',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'bird',       translation: 'kuş',          language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'fish',       translation: 'balık',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'cow',        translation: 'inek',         language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'pig',        translation: 'domuz',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'hen',        translation: 'tavuk',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'bee',        translation: 'arı',          language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'ant',        translation: 'karınca',      language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'red',        translation: 'kırmızı',      language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'blue',       translation: 'mavi',         language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'white',      translation: 'beyaz',        language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'black',      translation: 'siyah',        language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'one',        translation: 'bir',          language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'two',        translation: 'iki',          language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'three',      translation: 'üç',           language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'four',       translation: 'dört',         language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'five',       translation: 'beş',          language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'six',        translation: 'altı',         language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'ten',        translation: 'on',           language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'sun',        translation: 'güneş',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'moon',       translation: 'ay',           language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'star',       translation: 'yıldız',       language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'tree',       translation: 'ağaç',         language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'rain',       translation: 'yağmur',       language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'snow',       translation: 'kar',          language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'sea',        translation: 'deniz',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'fire',       translation: 'ateş',         language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'water',      translation: 'su',           language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'hand',       translation: 'el',           language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'eye',        translation: 'göz',          language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'ear',        translation: 'kulak',        language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'nose',       translation: 'burun',        language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'mouth',      translation: 'ağız',         language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'head',       translation: 'baş',          language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'leg',        translation: 'bacak',        language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'arm',        translation: 'kol',          language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'book',       translation: 'kitap',        language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'pen',        translation: 'kalem',        language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'bag',        translation: 'çanta',        language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'cup',        translation: 'fincan',       language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'door',       translation: 'kapı',         language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'bed',        translation: 'yatak',        language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  { word: 'car',        translation: 'araba',        language: 'ENGLISH', tier: 'A', category: 'transport',  cefrLevel: 'A1' },
  { word: 'bus',        translation: 'otobüs',       language: 'ENGLISH', tier: 'A', category: 'transport',  cefrLevel: 'A1' },
  { word: 'eat',        translation: 'yemek',        language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A1' },
  { word: 'run',        translation: 'koşmak',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A1' },
  { word: 'sit',        translation: 'oturmak',      language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A1' },
  { word: 'go',         translation: 'gitmek',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A1' },
  { word: 'see',        translation: 'görmek',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A1' },
  { word: 'big',        translation: 'büyük',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'hot',        translation: 'sıcak',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'old',        translation: 'yaşlı',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'new',        translation: 'yeni',         language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'good',       translation: 'iyi',          language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'bad',        translation: 'kötü',         language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },
  { word: 'fast',       translation: 'hızlı',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A1' },

  // ─── TIER A — BRONZ (A2) ───────────────────────────────────────────────
  { word: 'horse',      translation: 'at',           language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'rabbit',     translation: 'tavşan',       language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'snake',      translation: 'yılan',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'tiger',      translation: 'kaplan',       language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'lion',       translation: 'aslan',        language: 'ENGLISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'green',      translation: 'yeşil',        language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'yellow',     translation: 'sarı',         language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'orange',     translation: 'turuncu',      language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'purple',     translation: 'mor',          language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'brown',      translation: 'kahverengi',   language: 'ENGLISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'seven',      translation: 'yedi',         language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A2' },
  { word: 'eight',      translation: 'sekiz',        language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A2' },
  { word: 'nine',       translation: 'dokuz',        language: 'ENGLISH', tier: 'A', category: 'numbers',    cefrLevel: 'A2' },
  { word: 'cloud',      translation: 'bulut',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'wind',       translation: 'rüzgar',       language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'river',      translation: 'nehir',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'mountain',   translation: 'dağ',          language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'flower',     translation: 'çiçek',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'forest',     translation: 'orman',        language: 'ENGLISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'shoulder',   translation: 'omuz',         language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A2' },
  { word: 'finger',     translation: 'parmak',       language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A2' },
  { word: 'tooth',      translation: 'diş',          language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A2' },
  { word: 'hair',       translation: 'saç',          language: 'ENGLISH', tier: 'A', category: 'body',       cefrLevel: 'A2' },
  { word: 'window',     translation: 'pencere',      language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A2' },
  { word: 'table',      translation: 'masa',         language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A2' },
  { word: 'chair',      translation: 'sandalye',     language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A2' },
  { word: 'clock',      translation: 'saat',         language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A2' },
  { word: 'phone',      translation: 'telefon',      language: 'ENGLISH', tier: 'A', category: 'objects',    cefrLevel: 'A2' },
  { word: 'shoe',       translation: 'ayakkabı',     language: 'ENGLISH', tier: 'A', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'shirt',      translation: 'gömlek',       language: 'ENGLISH', tier: 'A', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'hat',        translation: 'şapka',        language: 'ENGLISH', tier: 'A', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'dress',      translation: 'elbise',       language: 'ENGLISH', tier: 'A', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'bread',      translation: 'ekmek',        language: 'ENGLISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'milk',       translation: 'süt',          language: 'ENGLISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'apple',      translation: 'elma',         language: 'ENGLISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'rice',       translation: 'pirinç',       language: 'ENGLISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'egg',        translation: 'yumurta',      language: 'ENGLISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'train',      translation: 'tren',         language: 'ENGLISH', tier: 'A', category: 'transport',  cefrLevel: 'A2' },
  { word: 'plane',      translation: 'uçak',         language: 'ENGLISH', tier: 'A', category: 'transport',  cefrLevel: 'A2' },
  { word: 'swim',       translation: 'yüzmek',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'jump',       translation: 'zıplamak',     language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'sleep',      translation: 'uyumak',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'write',      translation: 'yazmak',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'read',       translation: 'okumak',       language: 'ENGLISH', tier: 'A', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'small',      translation: 'küçük',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'cold',       translation: 'soğuk',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'tall',       translation: 'uzun boylu',   language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'short',      translation: 'kısa',         language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'happy',      translation: 'mutlu',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'sad',        translation: 'üzgün',        language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'tired',      translation: 'yorgun',       language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'hungry',     translation: 'aç',           language: 'ENGLISH', tier: 'A', category: 'adjectives', cefrLevel: 'A2' },

  // ─── TIER B — GÜMÜŞ (A2 advanced / B1 başlangıç) ─────────────────────
  { word: 'dolphin',    translation: 'yunus',        language: 'ENGLISH', tier: 'B', category: 'animals',    cefrLevel: 'A2' },
  { word: 'penguin',    translation: 'penguen',      language: 'ENGLISH', tier: 'B', category: 'animals',    cefrLevel: 'A2' },
  { word: 'eagle',      translation: 'kartal',       language: 'ENGLISH', tier: 'B', category: 'animals',    cefrLevel: 'B1' },
  { word: 'wolf',       translation: 'kurt',         language: 'ENGLISH', tier: 'B', category: 'animals',    cefrLevel: 'B1' },
  { word: 'desert',     translation: 'çöl',          language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'A2' },
  { word: 'island',     translation: 'ada',          language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'A2' },
  { word: 'valley',     translation: 'vadi',         language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'B1' },
  { word: 'storm',      translation: 'fırtına',      language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'B1' },
  { word: 'thunder',    translation: 'gök gürültüsü',language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'B1' },
  { word: 'shadow',     translation: 'gölge',        language: 'ENGLISH', tier: 'B', category: 'nature',     cefrLevel: 'B1' },
  { word: 'prison',     translation: 'hapishane',    language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'B1' },
  { word: 'factory',    translation: 'fabrika',      language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'B1' },
  { word: 'library',    translation: 'kütüphane',    language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'A2' },
  { word: 'hospital',   translation: 'hastane',      language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'A2' },
  { word: 'airport',    translation: 'havalimanı',   language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'A2' },
  { word: 'kitchen',    translation: 'mutfak',       language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'A2' },
  { word: 'bedroom',    translation: 'yatak odası',  language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'A2' },
  { word: 'basement',   translation: 'bodrum',       language: 'ENGLISH', tier: 'B', category: 'places',     cefrLevel: 'B1' },
  { word: 'explain',    translation: 'açıklamak',    language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'decide',     translation: 'karar vermek', language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'remember',   translation: 'hatırlamak',   language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'forget',     translation: 'unutmak',      language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'A2' },
  { word: 'choose',     translation: 'seçmek',       language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'prepare',    translation: 'hazırlamak',   language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'increase',   translation: 'artırmak',     language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'decrease',   translation: 'azaltmak',     language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'compare',    translation: 'karşılaştırmak',language: 'ENGLISH',tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'suggest',    translation: 'önermek',      language: 'ENGLISH', tier: 'B', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'nervous',    translation: 'gergin',       language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'patient',    translation: 'sabırlı',      language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'brave',      translation: 'cesur',        language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'honest',     translation: 'dürüst',       language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'polite',     translation: 'nazik',        language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'lazy',       translation: 'tembel',       language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'smart',      translation: 'akıllı',       language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'A2' },
  { word: 'careful',    translation: 'dikkatli',     language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'dangerous',  translation: 'tehlikeli',    language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'comfortable',translation: 'rahat',        language: 'ENGLISH', tier: 'B', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'shoulder bag',translation:'omuz çantası', language: 'ENGLISH', tier: 'B', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'jacket',     translation: 'ceket',        language: 'ENGLISH', tier: 'B', category: 'clothing',   cefrLevel: 'A2' },
  { word: 'suit',       translation: 'takım elbise', language: 'ENGLISH', tier: 'B', category: 'clothing',   cefrLevel: 'B1' },
  { word: 'vegetable',  translation: 'sebze',        language: 'ENGLISH', tier: 'B', category: 'food',       cefrLevel: 'A2' },
  { word: 'sugar',      translation: 'şeker',        language: 'ENGLISH', tier: 'B', category: 'food',       cefrLevel: 'A2' },
  { word: 'butter',     translation: 'tereyağı',     language: 'ENGLISH', tier: 'B', category: 'food',       cefrLevel: 'B1' },
  { word: 'pepper',     translation: 'biber',        language: 'ENGLISH', tier: 'B', category: 'food',       cefrLevel: 'B1' },
  { word: 'recipe',     translation: 'tarif',        language: 'ENGLISH', tier: 'B', category: 'food',       cefrLevel: 'B1' },

  // ─── TIER C — ALTIN (B1 / B2) ──────────────────────────────────────────
  { word: 'phenomenon',  translation: 'fenomen',      language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B2' },
  { word: 'evidence',    translation: 'kanıt',        language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B1' },
  { word: 'hypothesis',  translation: 'hipotez',      language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B2' },
  { word: 'analysis',    translation: 'analiz',       language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B2' },
  { word: 'research',    translation: 'araştırma',    language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B1' },
  { word: 'theory',      translation: 'teori',        language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B1' },
  { word: 'principle',   translation: 'ilke',         language: 'ENGLISH', tier: 'C', category: 'academic',   cefrLevel: 'B2' },
  { word: 'significant', translation: 'önemli',       language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B2' },
  { word: 'essential',   translation: 'temel',        language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'efficient',   translation: 'verimli',      language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B2' },
  { word: 'flexible',    translation: 'esnek',        language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B2' },
  { word: 'consistent',  translation: 'tutarlı',      language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B2' },
  { word: 'relevant',    translation: 'alakalı',      language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B2' },
  { word: 'complex',     translation: 'karmaşık',     language: 'ENGLISH', tier: 'C', category: 'adjectives', cefrLevel: 'B1' },
  { word: 'achieve',     translation: 'başarmak',     language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'analyze',     translation: 'analiz etmek', language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'establish',   translation: 'kurmak',       language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'evaluate',    translation: 'değerlendirmek',language: 'ENGLISH',tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'implement',   translation: 'uygulamak',    language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'influence',   translation: 'etkilemek',    language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'indicate',    translation: 'belirtmek',    language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'maintain',    translation: 'sürdürmek',    language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'obtain',      translation: 'elde etmek',   language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'perceive',    translation: 'algılamak',    language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'convince',    translation: 'ikna etmek',   language: 'ENGLISH', tier: 'C', category: 'verbs',      cefrLevel: 'B1' },
  { word: 'consequence', translation: 'sonuç',        language: 'ENGLISH', tier: 'C', category: 'nouns',      cefrLevel: 'B2' },
  { word: 'opportunity', translation: 'fırsat',       language: 'ENGLISH', tier: 'C', category: 'nouns',      cefrLevel: 'B1' },
  { word: 'challenge',   translation: 'zorluk',       language: 'ENGLISH', tier: 'C', category: 'nouns',      cefrLevel: 'B1' },
  { word: 'perspective', translation: 'perspektif',   language: 'ENGLISH', tier: 'C', category: 'nouns',      cefrLevel: 'B2' },
  { word: 'diversity',   translation: 'çeşitlilik',   language: 'ENGLISH', tier: 'C', category: 'nouns',      cefrLevel: 'B2' },

  // ─── TIER MASTER — EFSANE (B2 / C1) ───────────────────────────────────
  { word: 'ambiguous',   translation: 'belirsiz',     language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'eloquent',    translation: 'belagatlı',    language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'pragmatic',   translation: 'pragmatik',    language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'profound',    translation: 'derin',        language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'subtle',      translation: 'ince',         language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'coherent',    translation: 'tutarlı',      language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'inherent',    translation: 'doğal',        language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'meticulous',  translation: 'titiz',        language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'versatile',   translation: 'çok yönlü',    language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'resilient',   translation: 'dayanıklı',    language: 'ENGLISH', tier: 'MASTER', category: 'adjectives', cefrLevel: 'C1' },
  { word: 'acknowledge', translation: 'kabul etmek',  language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'B2' },
  { word: 'anticipate',  translation: 'öngörmek',     language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'articulate',  translation: 'ifade etmek',  language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'contemplate', translation: 'düşünmek',     language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'undermine',   translation: 'zayıflatmak',  language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'embody',      translation: 'somutlaştırmak',language: 'ENGLISH',tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'endeavour',   translation: 'gayret etmek', language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'scrutinize',  translation: 'incelemek',    language: 'ENGLISH', tier: 'MASTER', category: 'verbs',      cefrLevel: 'C1' },
  { word: 'ambiguity',   translation: 'belirsizlik',  language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'C1' },
  { word: 'paradigm',    translation: 'paradigma',    language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'C1' },
  { word: 'integrity',   translation: 'dürüstlük',    language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'B2' },
  { word: 'sovereignty', translation: 'egemenlik',    language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'C1' },
  { word: 'rhetoric',    translation: 'retorik',      language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'C1' },
  { word: 'dilemma',     translation: 'ikilem',       language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'B2' },
  { word: 'nuance',      translation: 'nüans',        language: 'ENGLISH', tier: 'MASTER', category: 'nouns',      cefrLevel: 'C1' },

  // ─── İSPANYOLCA A1 ────────────────────────────────────────────────────
  { word: 'gato',        translation: 'kedi',         language: 'SPANISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'perro',       translation: 'köpek',        language: 'SPANISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'pájaro',      translation: 'kuş',          language: 'SPANISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'pez',         translation: 'balık',        language: 'SPANISH', tier: 'A', category: 'animals',    cefrLevel: 'A1' },
  { word: 'rojo',        translation: 'kırmızı',      language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'azul',        translation: 'mavi',         language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'blanco',      translation: 'beyaz',        language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'negro',       translation: 'siyah',        language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A1' },
  { word: 'uno',         translation: 'bir',          language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'dos',         translation: 'iki',          language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'tres',        translation: 'üç',           language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'cuatro',      translation: 'dört',         language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'cinco',       translation: 'beş',          language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A1' },
  { word: 'sol',         translation: 'güneş',        language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'luna',        translation: 'ay',           language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'agua',        translation: 'su',           language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'árbol',       translation: 'ağaç',         language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A1' },
  { word: 'mano',        translation: 'el',           language: 'SPANISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'ojo',         translation: 'göz',          language: 'SPANISH', tier: 'A', category: 'body',       cefrLevel: 'A1' },
  { word: 'libro',       translation: 'kitap',        language: 'SPANISH', tier: 'A', category: 'objects',    cefrLevel: 'A1' },
  // İspanyolca A2
  { word: 'caballo',     translation: 'at',           language: 'SPANISH', tier: 'A', category: 'animals',    cefrLevel: 'A2' },
  { word: 'verde',       translation: 'yeşil',        language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'amarillo',    translation: 'sarı',         language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'naranja',     translation: 'turuncu',      language: 'SPANISH', tier: 'A', category: 'colors',     cefrLevel: 'A2' },
  { word: 'seis',        translation: 'altı',         language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A2' },
  { word: 'siete',       translation: 'yedi',         language: 'SPANISH', tier: 'A', category: 'numbers',    cefrLevel: 'A2' },
  { word: 'lluvia',      translation: 'yağmur',       language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'montaña',     translation: 'dağ',          language: 'SPANISH', tier: 'A', category: 'nature',     cefrLevel: 'A2' },
  { word: 'pan',         translation: 'ekmek',        language: 'SPANISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
  { word: 'leche',       translation: 'süt',          language: 'SPANISH', tier: 'A', category: 'food',       cefrLevel: 'A2' },
]

async function main() {
  console.log(`${words.length} kelime import ediliyor...`)

  let created = 0
  let updated = 0

  for (const word of words) {
    const existing = await prisma.word.findUnique({
      where: { language_word: { language: word.language as any, word: word.word } }
    })

    if (existing) {
      await prisma.word.update({
        where: { language_word: { language: word.language as any, word: word.word } },
        data: { cefrLevel: word.cefrLevel, category: word.category, translation: word.translation }
      })
      updated++
    } else {
      await prisma.word.create({ data: word as any })
      created++
    }
  }

  console.log(`✓ ${created} yeni kelime eklendi, ${updated} kelime güncellendi`)
  console.log(`✓ Toplam: ${words.length} kelime`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
